version: '3.8'
services:
  # Base de datos centralizada (usaremos diferentes esquemas o DBs)
  postgres-db:
    image: postgres:15
    container_name: postgres-db
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=auth_db
    ports:
      - "5432:5432"
    networks:
      - micro-network

  # Broker de mensajería para la comunicación asíncrona
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-service
    ports:
      - "8080:8080"   # Puerto de comunicación
      - "15672:15672" # Interfaz web de control
    networks:
      - micro-network

networks:
  micro-network:
    driver: bridge