
services:
  # Base de datos centralizada
  postgres-db:
    image: postgres:15
    container_name: postgres-db
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=auth_db
    ports:
      - "5432:5432"
    networks:
      - micro-network

  # Broker de mensajería
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-service
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - micro-network

  # Servicio de autenticación
  auth-service:
    build: ./auth-service
    container_name: auth-service
    ports:
      - "8080:8080"
    networks:
      - micro-network

  # Servicio biblioteca
  biblioteca-service:
    build: ./biblioteca-service
    container_name: biblioteca-service
    ports:
      - "8081:8081"
    networks:
      - micro-network

networks:
  micro-network:
    driver: bridge